preload = ~/Documents/wp.jpg
preload =  ~/Documents/test.jpg
preload =  ~/Pictures/saiki1.jpg
preload =  ~/Pictures/saiki2.jpg
preload =  ~/Pictures/dominik-mayer-24.jpg
preload =  ~/Documents/everforest.jpg
preload =  ~/Pictures/dominik-mayer-10.jpg
#wallpaper = DP-1, ~/Documents/everforest.jpg
wallpaper = DP-1, ~/Pictures/dominik-mayer-24.jpg
#wallpaper = DP-1, ~/Pictures/dominik-mayer-10.jpg
